server:
  port: 8090

spring:
  application:
    name: bz-ootd-service
  web:
    resources:
      static-locations: classpath:/static/

bzbzo:
  bz-auth-service-url: ${AUTH_SERVICE_URL:http://localhost:8085}/auths

