server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bz_ootd?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 12341234
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # 최대 파일 크기 설정
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true

bzbzo:
  bz-auth-service-url: ${AUTH_SERVICE_URL:http://localhost:8085}/auths
  bz-seller-service-url: ${SELLER_SERVICE_URL:http://localhost:8088}/
  bz-ootd-service-url: ${OOTD_SERVICE_URL:http://localhost:8090}/
  bz-edge-service-url: ${EDGE_SERVICE_URL:http://localhost:9999}/

cloud:
  aws:
    s3:
      bucket: bz-img-bucket
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}

web:
  resources:
    static-locations: classpath:/static/, file:./uploads/